### PR TITLE
add new maintainer

### PR DESCRIPTION
**Pull request by rluria14**
Checklist
    * [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
    * [x] Bumped the build number (if the version is unchanged)
    * [x] Reset the build number to `0` (if the version changed)
    * [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
    * [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
@rluria14 These PRs are quite confusing as you add someone that is not yourself .

**Comment by rluria14** [comment]
> @rluria14 These PRs are quite confusing as you add someone that is not yourself .

My team made the account as a group to follow all of the feedstocks we maintain

**Comment by xhochy** [comment]
Oh, team accounts. Not sure how to correctly handle that 🤔 In the Apache org I know that there is something explicitly preventing that but I don't think we have a policy here (yet). Could you please at least add some description to that account to make it less weird? 

Also I'm not feeling well merging this but also not objecting so I'll just leave it here as-is.

**Comment by wolfv** [comment]
@rluria14 is also not necessary to bump the build number when you're only adding a maintainer

**Comment by rluria14** [comment]
> Oh, team accounts. Not sure how to correctly handle that 🤔 In the Apache org I know that there is something explicitly preventing that but I don't think we have a policy here (yet). Could you please at least add some description to that account to make it less weird?
> 
> Also I'm not feeling well merging this but also not objecting so I'll just leave it here as-is.

Understood! We've added a description to the account.

**Comment by oblute** [comment]
> Oh, team accounts. Not sure how to correctly handle that 🤔 In the Apache org I know that there is something explicitly preventing that but I don't think we have a policy here (yet). Could you please at least add some description to that account to make it less weird?
> 
> Also I'm not feeling well merging this but also not objecting so I'll just leave it here as-is.

I'm a bit confused here especially by `I'm not feeling well merging this` - if @rluria14 and myself are maintainers on this (& 300+ feedstocks in the conda-forge) and we created an account here to help us better monitor and maintain all of these feedstocks going forward, and we already maintain this, can't we merge this?

**Comment by xhochy** [comment]
@oblute If you are part of that team or feel OK in general with that, then merge. @rluria14 is not a part of the feedstock here so he needs someone to merge. I'm just undecided ;)

**Comment by oblute** [comment]
@xhochy okay, thanks! didn't notice he wasn't a maintainer already.

**Pull request merged**
